from prettymaps import plot
import matplotlib.pyplot as plt
import io
from PIL import Image, ImageDraw, ImageFont

try:
    fig, ax = plt.subplots(figsize=(10, 10), dpi=300)
    plot_result = plot(
        'Oshino Hakkai, Yamanashi, Japan',
        preset='macao',
        circle=True,
        radius=600,
        show=False,
        credit=False,
        ax=ax
    )
    
    ax.axis('off')
    
    raw_buf = io.BytesIO()
    plt.savefig(raw_buf, format="png", bbox_inches="tight", pad_inches=0, dpi=150)
    raw_buf.seek(0)
    
    map_img = Image.open(raw_buf)
    map_w, map_h = map_img.size
    
    top_margin = 60
    bottom_margin = 40
    side_margin = 40
    
    final_w = map_w + (side_margin * 2)
    final_h = map_h + top_margin + bottom_margin
    final_img = Image.new("RGB", (final_w, final_h), "white")
    
    final_img.paste(map_img, (side_margin, top_margin))
    
    draw = ImageDraw.Draw(final_img)
    display_title = "OSHINO HAKKAI"
    
    try:
        font_title = ImageFont.truetype("DejaVuSerif-Bold.ttf", 32)
        font_footer = ImageFont.truetype("DejaVuSans.ttf", 14)
    except:
        font_title = ImageFont.load_default()
        font_footer = ImageFont.load_default()
        
    draw.text((side_margin, 15), display_title, fill="#2F3737", font=font_title)
    draw.text((side_margin, top_margin + map_h + 10), "Map data © OpenStreetMap contributors | Generated by Prettymaps", fill="#475657", font=font_footer)
    
    final_img.save('/tmp/Oshino_Hakkai_Map_Test_PIL.png')
    print("Map generated at /tmp/Oshino_Hakkai_Map_Test_PIL.png")
except Exception as e:
    print(f"Error: {e}")
