from prettymaps import plot
import matplotlib.pyplot as plt
import os

try:
    fig, ax = plt.subplots(figsize=(10, 10), dpi=300)
    plot_result = plot(
        'Oshino Hakkai, Yamanashi, Japan',
        preset='macao',
        circle=True,
        radius=600,
        show=False,
        credit=False,
        ax=ax
    )
    
    display_title = "OSHINO HAKKAI"
    fig.text(0.5, 1.015, display_title, ha='center', va='bottom', fontsize=32, fontweight='bold', fontfamily='serif', color='#2F3737')
    fig.text(0.5, -0.015, "Map data © OpenStreetMap contributors | Generated by Prettymaps", ha='center', va='top', fontsize=12, fontfamily='sans-serif', color='#475657')
    
    os.makedirs('/root/Obsidian/Travel', exist_ok=True)
    plt.savefig('/root/Obsidian/Travel/Oshino_Hakkai_Map.png', format="png", bbox_inches="tight", pad_inches=0.4, dpi=150)
    print("Map generated at /root/Obsidian/Travel/Oshino_Hakkai_Map.png")
except Exception as e:
    print(f"Error: {e}")
